Repository boostcamp-2020/Project17-A-Map, pull requests merged in 2020-11, with the labels that each got.

#3 [docs] Update README.md
  README.md
Labels: documentation

#19 1주차 Merge to master
  .gitignore
  NaverMapA/NaverMapA.xcodeproj/project.pbxproj
  NaverMapA/NaverMapA/AppDelegate.swift
  NaverMapA/NaverMapA/Assets.xcassets/restaurant_list.dataset/Contents.json
  NaverMapA/NaverMapA/Assets.xcassets/restaurant_list.dataset/restaurant_list.json
  NaverMapA/NaverMapA/Model/CoreDataManager.swift
  NaverMapA/NaverMapA/Model/JsonPlace.swift
  NaverMapA/NaverMapA/Model/NaverMapA.xcdatamodeld/.xccurrentversion
  NaverMapA/NaverMapA/Model/NaverMapA.xcdatamodeld/NaverMapA.xcdatamodel/contents
  NaverMapA/NaverMapA/NaverMapA.xcdatamodeld/NaverMapA.xcdatamodel/contents
  NaverMapA/NaverMapA/ViewController.swift
  NaverMapA/Place+CoreDataClass.swift
  NaverMapA/Place+CoreDataProperties.swift
Labels: Merge:master

#24 Kim's Clustering 구현
  NaverMapA/NaverMapA.xcodeproj/project.pbxproj
  NaverMapA/NaverMapA/Controller/MainViewController.swift
  NaverMapA/NaverMapA/Model/Cluster.swift
  NaverMapA/NaverMapA/Model/JsonPlace.swift
  NaverMapA/NaverMapA/Model/PlaceProvider.swift
  NaverMapA/NaverMapA/Model/ScaleBasedClustering.swift
Labels: enhancement

#28 [Fix] 메모리 충돌 문제 해결
  NaverMapA/NaverMapA/Controller/MainViewController.swift
Labels: bug

#25 [docs] Readme에 프로젝트 소개, 기술 목표 추가
  README.md
Labels: documentation

#31 2주차 Merge to master
  NaverMapA/.swiftlint.yml
  NaverMapA/NaverMapA.xcodeproj/project.pbxproj
  NaverMapA/NaverMapA.xcworkspace/contents.xcworkspacedata
  NaverMapA/NaverMapA/AppDelegate.swift
  NaverMapA/NaverMapA/Base.lproj/Main.storyboard
  NaverMapA/NaverMapA/Controller/MainViewController+NMFOverlayImageDataSource.swift
  NaverMapA/NaverMapA/Controller/MainViewController.swift
  NaverMapA/NaverMapA/Model/Cluster.swift
  NaverMapA/NaverMapA/Model/Clustering.swift
  NaverMapA/NaverMapA/Model/CoordinateBounds.swift
  NaverMapA/NaverMapA/Model/CoreDataManager.swift
  NaverMapA/NaverMapA/Model/JsonPlace.swift
  NaverMapA/NaverMapA/Model/KMeansClustering.swift
  NaverMapA/NaverMapA/Model/PlaceProvider.swift
  NaverMapA/NaverMapA/Model/ScaleBasedClustering.swift
  NaverMapA/NaverMapA/SceneDelegate.swift
  NaverMapA/NaverMapA/Util/Environment.swift
  NaverMapA/NaverMapA/ViewController.swift
  NaverMapA/NaverMapA/ViewModel/Dynamic.swift
  NaverMapA/NaverMapA/ViewModel/MainViewModel.swift
  NaverMapA/Place+CoreDataClass.swift
  NaverMapA/Place.swift
Labels: Merge:master
