Repository boostcamp-2020/Project17-A-Map, pull requests merged in 2020-12, with the labels that each got.

#32 [feat] 마커 터치 시 카메라 이동 함수 구현
  NaverMapA/NaverMapA/Controller/MainViewController.swift
Labels: enhancement

#34 마커 애니메이션 수정
  NaverMapA/NaverMapA.xcodeproj/project.pbxproj
  NaverMapA/NaverMapA/Controller/MainViewController+NMFMapViewCameraDelegate.swift
  NaverMapA/NaverMapA/Controller/MainViewController+NMFOverlayImageDataSource.swift
  NaverMapA/NaverMapA/Controller/MainViewController.swift
  NaverMapA/NaverMapA/Model/Cluster.swift
  NaverMapA/NaverMapA/Model/JsonPlace.swift
  NaverMapA/NaverMapA/ViewModel/MainViewModel.swift
Labels: enhancement

#38 [feat] 마커 생성 시 애니메이션 구현 및 줌 버튼 추가
  NaverMapA/NaverMapA/Controller/MainViewController+Animation.swift
  NaverMapA/NaverMapA/Controller/MainViewController.swift
Labels: enhancement

#44 3주차 Merge to master
  NaverMapA/NaverMapA.xcodeproj/project.pbxproj
  NaverMapA/NaverMapA.xcodeproj/xcshareddata/xcschemes/NaverMapA.xcscheme
  NaverMapA/NaverMapA/Base.lproj/Main.storyboard
  NaverMapA/NaverMapA/Controller/DetailPullUpViewController.swift
  NaverMapA/NaverMapA/Controller/MainViewController+Animation.swift
  NaverMapA/NaverMapA/Controller/MainViewController+NMFMapViewCameraDelegate.swift
  NaverMapA/NaverMapA/Controller/MainViewController+NMFOverlayImageDataSource.swift
  NaverMapA/NaverMapA/Controller/MainViewController+PullUpViewDelegate.swift
  NaverMapA/NaverMapA/Controller/MainViewController.swift
  NaverMapA/NaverMapA/Model/Algorithm/Clusterable.swift
  NaverMapA/NaverMapA/Model/Algorithm/KMeansClustering.swift
  NaverMapA/NaverMapA/Model/Algorithm/ScaleBasedClustering.swift
  NaverMapA/NaverMapA/Model/Algorithm/penaltyKmeans.swift
  NaverMapA/NaverMapA/Model/Cluster/BasicCluster.swift
  NaverMapA/NaverMapA/Model/Cluster/Cluster.swift
  NaverMapA/NaverMapA/Model/Cluster/PenaltyCluster.swift
  NaverMapA/NaverMapA/Model/Marker/MarkerFactory.swift
  NaverMapA/NaverMapA/Model/Place/CoordinateBounds.swift
  NaverMapA/NaverMapA/Model/Place/JsonPlace.swift
  NaverMapA/NaverMapA/Model/Place/NaverMapA.xcdatamodeld/.xccurrentversion
  NaverMapA/NaverMapA/Model/Place/NaverMapA.xcdatamodeld/NaverMapA.xcdatamodel/contents
  NaverMapA/NaverMapA/Model/Place/Place.swift
  NaverMapA/NaverMapA/Model/Place/PlaceProvider.swift
  NaverMapA/NaverMapA/View/DetailCollectionViewDetailCell.swift
  NaverMapA/NaverMapA/View/DetailCollectionViewDetailCell.xib
  NaverMapA/NaverMapA/View/DetailCollectionViewListCell.swift
  NaverMapA/NaverMapA/View/DetailCollectionViewListCell.xib
  NaverMapA/NaverMapA/ViewModel/DetailCollectionViewDataSource.swift
  NaverMapA/NaverMapA/ViewModel/DetailViewModel.swift
  NaverMapA/NaverMapA/ViewModel/MainViewModel.swift
  NaverMapA/NaverMapATests/RemainKMeansTest.swift
  NaverMapA/NaverMapAUITests/NaverMapAUITests.swift
Labels: Merge:master

#49 애니메이션 버그 수정
  NaverMapA/NaverMapA/Controller/MainViewController+Animation.swift
  NaverMapA/NaverMapA/Controller/MainViewController.swift
Labels: bug

#64 [fix] 움직일 때 beforeMarkers에 넣는 방식으로 해결
  NaverMapA/NaverMapA/ViewModel/MainViewModel.swift
Labels: bug🤦‍♂️

#66 [Fix] Navigator Bar 오류 해결
  NaverMapA/NaverMapA/Controller/MainViewController.swift
  NaverMapA/NaverMapA/Controller/SettingTableViewController.swift
  NaverMapA/NaverMapA/Util/AlertManager.swift
Labels: bug🤦‍♂️

#70 동적인 애니메이션 및 마커 색상 변경
  NaverMapA/NaverMapA.xcodeproj/project.pbxproj
  NaverMapA/NaverMapA/Base.lproj/Main.storyboard
  NaverMapA/NaverMapA/Controller/MainViewController+NaverMap.swift
  NaverMapA/NaverMapA/Controller/MainViewController.swift
  NaverMapA/NaverMapA/Controller/SettingTableViewController.swift
  NaverMapA/NaverMapA/Model/Animator/Animator.swift
  NaverMapA/NaverMapA/Model/Marker/GetMarkerColor.swift
  NaverMapA/NaverMapA/Model/Marker/MarkerFactory.swift
  NaverMapA/NaverMapA/Model/Marker/NaverMapView.swift
  NaverMapA/NaverMapA/Model/Marker/VHCTextLayer.swift
  NaverMapA/NaverMapA/Model/PropertyWrapper/AtomicArray.swift
  NaverMapA/NaverMapA/Model/PropertyWrapper/UserInfo.swift
  NaverMapA/NaverMapA/Util/UIView+Rendering.swift
  NaverMapA/NaverMapA/View/SettingTableViewCell.swift
  NaverMapA/NaverMapA/View/SettingTableViewCell.xib
Labels: enhancement

#79 버그 수정
  NaverMapA/NaverMapA/Controller/MainViewController+NaverMap.swift
  NaverMapA/NaverMapA/Controller/MainViewController.swift
  NaverMapA/NaverMapA/Controller/SettingTableViewController.swift
  NaverMapA/NaverMapA/Model/Marker/GetMarkerColor.swift
  NaverMapA/NaverMapA/Model/Marker/NaverMapView.swift
  NaverMapA/NaverMapA/Model/Place/PlaceProvider.swift
  NaverMapA/NaverMapA/View/SettingTableViewCell.swift
Labels: bug🤦‍♂️

#73 [Feat] Leaf Node 터치 시 인터렉션 구현
  NaverMapA/NaverMapA/Controller/MainViewController+NaverMap.swift
  NaverMapA/NaverMapA/Controller/MainViewController+PullUpViewDelegate.swift
  NaverMapA/NaverMapA/Controller/MainViewController.swift
  NaverMapA/NaverMapA/Model/Marker/NaverMapView.swift
  NaverMapA/NaverMapA/ViewModel/DetailCollectionViewDataSource.swift
  NaverMapA/NaverMapA/ViewModel/MainViewModel.swift
Labels: enhancement

#83 [fix] SettingView Cell 깨지는거 수정
  NaverMapA/NaverMapA/View/SettingTableViewCell.swift
  NaverMapA/NaverMapA/View/SettingTableViewCell.xib
Labels: bug🤦‍♂️

#85 README_최종_최종
  README.md
Labels: documentation

#87 [fix] 폴업 뷰에서 터치 시 애니메이션 안되던 버그 수정
  NaverMapA/NaverMapA/Controller/MainViewController+NaverMap.swift
  NaverMapA/NaverMapA/Controller/MainViewController+PullUpViewDelegate.swift
  NaverMapA/NaverMapA/Controller/MainViewController.swift
  NaverMapA/NaverMapA/Model/Marker/NaverMapView.swift
  NaverMapA/NaverMapA/ViewModel/MainViewModel.swift
Labels: bug🤦‍♂️
